name: "Payroll Assistant"
userId: "f6b917a9-e0ba-40f4-bcad-4702f69aff99"
status: "configured"
createdAt: "2026-01-28T23:18:52.138Z"
updatedAt: "2026-01-28T23:18:52.138Z"
promptStyle: "custom"
description: ""