name: "Copy of Test Agent for Clone"
userId: "b96e4232-68cd-4d57-959b-9f5e5db895cb"
status: "configured"
createdAt: "2026-02-05T22:33:07.866Z"
updatedAt: "2026-02-05T22:33:07.866Z"
promptStyle: "gemini"
mockMode: "full"
description: ""