name: Copy of Custom Column Expression Builder
description: 
status: configured
promptStyle: gemini
mockMode: full
userId: 22e95869-718c-428a-a9ae-a4694723ac19
createdAt: 2026-02-18T16:24:20.136Z
updatedAt: 2026-02-18T16:24:20.136Z