name: "Payroll employee test 1"
status: configured
createdAt: 2026-01-27T17:10:59.073Z
updatedAt: 2026-01-27T17:10:59.073Z

businessUseCase: |
  Pay question

description: |
  You are a helpful agent that answer payroll question from employee

validationRules: |
  

guardrails: |
  
