name: "HCM Report Custom Column Builder"
userId: "d9fc5ee0-2c32-4e88-9479-9d95bcaf689c"
status: "configured"
createdAt: "2026-02-06T02:52:47.989Z"
updatedAt: "2026-02-06T02:52:47.989Z"
promptStyle: "gemini"
mockMode: "full"
description: ""