name: "Payroll employee test 1"
status: configured
createdAt: 2026-01-27T18:50:09.024Z
updatedAt: 2026-01-27T18:50:09.024Z

businessUseCase: |
  this agent answers all employee pay related questions

description: |
  You are a helpful payroll information agent. You can answer any payroll related question when an employee has queries

validationRules: |
  

guardrails: |
  
