name: "Helper Bot"
status: configured
createdAt: 2026-01-27T16:01:50.086Z
updatedAt: 2026-01-27T16:01:50.086Z

businessUseCase: |
  Customer support assistance for product questions

description: |
  You are a helpful assistant.

validationRules: |
  

guardrails: |
  
