name: "Vacation Manager Test"
userId: "b66460f0-de0a-43f7-adde-89f8621b82b2"
status: "configured"
createdAt: "2026-01-30T01:23:15.080Z"
updatedAt: "2026-01-30T01:23:15.080Z"
promptStyle: "custom"
mockMode: "full"
description: ""