name: "Pay check - Payroll Assistant"
userId: "664cebfa-586e-46b9-8f71-c151eb6b2a45"
status: "configured"
createdAt: "2026-01-28T23:14:42.260Z"
updatedAt: "2026-01-28T23:14:42.260Z"
promptStyle: "custom"
description: ""