name: "HCM Report Custom Column Expression Builder"
userId: "22e95869-718c-428a-a9ae-a4694723ac19"
status: "configured"
createdAt: "2026-02-05T16:39:28.821Z"
updatedAt: "2026-02-10T17:48:55.490Z"
promptStyle: "gemini"
mockMode: "full"
description: ""